# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'TerraformInitPlan'
    jobs:
      - job: 'TerraformInit'
        
        steps:
          - bash: |
              terraform init
            workingDirectory: 'iac'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
          - bash: |
              terraform plan -out=plan.json
            workingDirectory: 'iac'
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)
          - task: publishPipelineArtifact@0
            inputs:
              artifactName: plan
              targetPath: 'iac/plan.json'
  - stage: TerraformApply
    jobs:
      - deployment: Apply
        environment: Test
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: plan
                  
                - bash: |
                    terraform init \
                    terraform apply plan.json
                  workingDirectory: 'iac'
                  env:
                    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY)
                    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)